Update QR generation sequence diagram
AY2324S2-CS2103T-T17-3/tp pull request #216
Opened 2024-03-31 05:43 UTC by dillontkh

New diagram:
![image](https://github.com/AY2324S2-CS2103T-T17-3/tp/assets/40649376/8df8b850-0e49-4741-8f2d-5a4f1bb526bd)

Resolves #213

2024-03-31 05:48 UTC, jjchee77 approved these changes
LGTM!

2024-04-02 02:47 UTC, RyanNgWH requested changes

2024-04-02 02:47 UTC, RyanNgWH commented on docs/diagrams/QrAddPersonSequenceDiagram.puml
>  Model -> Person : p.generateQrCode()
Should the `p` here be removed as well?

2024-04-02 03:11 UTC, dillontkh commented on docs/diagrams/QrAddPersonSequenceDiagram.puml
>  Model -> Person : p.generateQrCode()
Yes it should, good catch!

2024-04-03 12:30 UTC, RyanNgWH approved these changes
LGTM!

2024-04-03 12:30 UTC, merged