Add too dense QR code problem to known issues
AY2324S2-CS2103T-T17-3/tp pull request #314
Opened 2024-04-09 06:01 UTC by dillontkh

<img width="802" alt="image" src="https://github.com/AY2324S2-CS2103T-T17-3/tp/assets/40649376/06b818d0-df1f-4cc4-b11b-9378f680dc5f">

Resolves #299

2024-04-09 10:49 UTC, jjchee77 commented
This sounds like it could potentially be marked as a feature flaw during the PE, should we mention something about it in planned enhancement?

2024-04-10 15:00 UTC, ruijietay requested changes

2024-04-10 15:00 UTC, ruijietay commented on docs/UserGuide.md
> +> We have verified that the QR code can still be scanned for clients with no more than 100 characters in the following fields:
```suggestion
> We have verified that the QR code can still be scanned for clients with no more than 100 characters in each of the following fields:
```

2024-04-10 15:07 UTC, RyanNgWH approved these changes
lgtm

2024-04-10 15:09 UTC, ruijietay approved these changes
LGTM

2024-04-10 15:13 UTC, bgopi23 approved these changes

2024-04-10 15:15 UTC, merged