Docs: Add acknowledgements
AY2324S2-CS2103T-T17-3/tp pull request #340
Opened 2024-04-11 10:25 UTC by bgopi23

Added acknowledgements for me and @dillontkh

2024-04-11 10:36 UTC, dillontkh requested changes
Thanks! Just 1 markdown fix required.

2024-04-11 10:36 UTC, dillontkh commented on docs/DeveloperGuide.md
> +| Codeium | Dillon          | <li> JavaDocs <li> Full-line autocomplete |
Before:
<img width="751" alt="image" src="https://github.com/AY2324S2-CS2103T-T17-3/tp/assets/40649376/159cb5da-bc78-448c-81d7-ac76175d7774">

After:
<img width="755" alt="image" src="https://github.com/AY2324S2-CS2103T-T17-3/tp/assets/40649376/9fa6a972-ba08-470b-a3b6-7c651ed166c8">


```suggestion
| Codeium | Dillon          | {::nomarkdown}<ul><li>JavaDocs</li><li>Full-line autocomplete</li></ul>{:/} |
```

2024-04-11 12:37 UTC, dillontkh approved these changes
LGTM!

2024-04-11 17:32 UTC, jjchee77 approved these changes
LGTM!

2024-04-13 10:47 UTC, RyanNgWH approved these changes
LGTM!

2024-04-13 12:40 UTC, merged